const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const STORE_KEY = 'zentrik_shotlist_v1';
const GROUPS = {
  space:{title:'Space & ambience',icon:'⌂'}, food:{title:'Food & menu',icon:'✳'}, experience:{title:'Customer experience',icon:'♡'}, promo:{title:'Offer or promotion',icon:'↗'}, story:{title:'Brand story',icon:'✎'}, general:{title:'Extra shots',icon:'＋'}
};
const SHOTS = [
 // SPACE & ATMOSPHERE
 {group:'space',title:'Exterior establishing wide',instruction:'Film the full frontage and surroundings in a steady wide frame. Hold 5–8 seconds; capture a clean version without people crossing if possible.',tag:'Establishing / wide'},
 {group:'space',title:'Restaurant sign hero shot',instruction:'Frame the name/logo cleanly. Get one straight-on shot and one angled shot; avoid cutting off letters.',tag:'Brand detail'},
 {group:'space',title:'Approach to entrance',instruction:'Move slowly towards the entrance or follow someone walking in. Keep the horizon level and movement deliberate.',tag:'Gimbal push-in'},
 {group:'space',title:'Door opening / entering POV',instruction:'Film the door opening and reveal the space from a guest’s point of view. Capture a static take and a moving take.',tag:'POV / reveal'},
 {group:'space',title:'Interior reveal — wide',instruction:'Start behind a doorway, wall or foreground object, then reveal the room with a slow slide or push. Keep the move smooth.',tag:'Cinematic reveal'},
 {group:'space',title:'Interior slow pan',instruction:'Pan slowly across seating, decor and atmosphere. Begin and end on a composed frame; do not whip the camera.',tag:'Pan'},
 {group:'space',title:'Gimbal walkthrough',instruction:'Walk through the space at a controlled pace, using foreground elements to create depth. Record a second route if the room allows.',tag:'Tracking move'},
 {group:'space',title:'Table-level ambience',instruction:'Shoot from seated guest height across a table towards the room. Include foreground glassware or a menu for depth.',tag:'Guest POV'},
 {group:'space',title:'Lighting and decor details',instruction:'Capture 3–5 details: pendant lights, wall art, plants, textures, table settings or distinctive design elements.',tag:'Detail montage'},
 {group:'space',title:'Empty table setting',instruction:'Frame cutlery, napkin, glassware, menu and table finish neatly. Shoot from 45 degrees and overhead if practical.',tag:'Composition'},
 {group:'space',title:'Busy atmosphere / service rhythm',instruction:'Capture natural movement in the room: staff moving, dishes passing or guests chatting. Avoid identifiable guests without permission.',tag:'Atmosphere'},
 {group:'space',title:'Window / natural-light shot',instruction:'Show the space near a window or a patch of natural light. Expose for the scene and hold a few seconds.',tag:'Mood'},
 // FOOD — COVERAGE AND ANGLES
 {group:'food',title:'Hero dish — clean static frame',instruction:'Start with the full dish beautifully plated. Hold still for 5–8 seconds before any movement; leave breathing room around the plate.',tag:'Hero / master'},
 {group:'food',title:'Hero dish — slow push-in',instruction:'Move slowly towards the dish, finishing on the most appetising part. Keep the move straight and repeat at two speeds.',tag:'Push-in'},
 {group:'food',title:'Hero dish — pull-back reveal',instruction:'Begin tight on a texture or garnish and slowly pull back to reveal the complete plate or meal.',tag:'Reveal'},
 {group:'food',title:'45-degree food angle',instruction:'Shoot from a natural dining angle to show height, layers and toppings. Keep the plate edge intentional, not accidentally cropped.',tag:'Angle variation'},
 {group:'food',title:'Top-down / overhead food shot',instruction:'Shoot directly above the dish. Centre it or use a deliberate off-centre composition; keep phone/camera shadow out of frame.',tag:'Overhead'},
 {group:'food',title:'Low plate-level angle',instruction:'Get close to plate height to emphasise height, layers, steam or a stacked item. Check the background for clutter.',tag:'Low angle'},
 {group:'food',title:'Side profile / layers',instruction:'Show the side of the dish to reveal layers, filling, height or the amount of food. Particularly useful for burgers, cakes and layered meals.',tag:'Profile'},
 {group:'food',title:'Slow lateral food slide',instruction:'Slide left-to-right or right-to-left across the dish. Keep distance and speed consistent; use a foreground ingredient for depth.',tag:'Slider-style move'},
 {group:'food',title:'Food orbit / small arc',instruction:'Make a controlled 20–45 degree arc around the dish, keeping the hero item centred. Avoid a full orbit if the space is tight.',tag:'Orbit'},
 {group:'food',title:'Macro texture close-up',instruction:'Capture crisp, glossy, flaky, creamy or charred textures. Move close enough to show detail while keeping focus sharp.',tag:'Macro / texture'},
 {group:'food',title:'Ingredient detail montage',instruction:'Get separate close-ups of visible ingredients, toppings, herbs, cheese, vegetables or protein. Capture each for 3–5 seconds.',tag:'Detail montage'},
 {group:'food',title:'Fork / spoon / chopstick lift',instruction:'Lift one appealing bite slowly from the plate and hold it in focus. Get a clean take with the hand entering frame naturally.',tag:'Food action'},
 {group:'food',title:'Cut, crack or break open',instruction:'Cut through or break the item open to reveal its centre, filling or layers. Frame tightly and capture the action in real time and slow motion if available.',tag:'Reveal / texture'},
 {group:'food',title:'Stretch / pull shot',instruction:'If the food naturally stretches (cheese, noodles or similar), pull slowly and keep the stretch visible against a clean background.',tag:'Sensory action'},
 {group:'food',title:'Sauce drizzle / dip',instruction:'Film sauce being drizzled over the dish or a bite being dipped. Use a tight frame, controlled pour and a clean plate edge.',tag:'Pour / action'},
 {group:'food',title:'Garnish or finishing touch',instruction:'Capture a final sprinkle, herb placement, seasoning, glaze or finishing touch. Get close enough to see the movement clearly.',tag:'Finishing detail'},
 {group:'food',title:'Steam / heat moment',instruction:'If steam is naturally present, backlight it where possible and capture a stable close-up. Never create unsafe heat or fake food conditions.',tag:'Atmosphere'},
 {group:'food',title:'Plate landing on table',instruction:'Film the plate entering frame and landing on the table. Capture from guest POV and from a lower side angle.',tag:'Serving action'},
 {group:'food',title:'Hands arranging the meal',instruction:'Capture hands placing sides, adjusting cutlery, opening packaging or arranging the spread. Keep movement purposeful.',tag:'Lifestyle'},
 {group:'food',title:'Full meal / combo spread',instruction:'Show all items included in the meal or combo together. Keep quantities truthful and labels/packaging facing camera where relevant.',tag:'Menu / value'},
 {group:'food',title:'Food next to branded packaging',instruction:'Pair the food with a branded box, bag, bowl or wrapper. Keep the brand visible without hiding the dish.',tag:'Brand integration'},
 {group:'food',title:'Food in hand / handheld product',instruction:'Hold the item naturally in frame to communicate scale and portability. Capture a clean close-up and a wider lifestyle version.',tag:'Lifestyle'},
 {group:'food',title:'First bite reaction',instruction:'Film a genuine first bite and natural reaction. Ask permission, avoid forcing an exaggerated reaction and capture a wide and close version.',tag:'People / reaction'},
 {group:'food',title:'Taste / texture reaction detail',instruction:'Capture the moment after a bite: a smile, nod or natural expression. Keep it authentic and get consent from the person featured.',tag:'Reaction'},
 {group:'food',title:'Final appetising beauty shot',instruction:'Return to the best-looking angle after action shots. Clean the frame, check highlights and record a steady version for the edit or cover.',tag:'Safety hero take'},
 // KITCHEN / PREPARATION / CINEMATIC ACTION
 {group:'story',title:'Kitchen wide establishing shot',instruction:'Show the working kitchen and its rhythm from a safe, permitted position. Keep the frame composed and avoid interfering with staff.',tag:'Behind the scenes'},
 {group:'story',title:'Chef hands preparing ingredients',instruction:'Close in on hands washing, chopping, slicing, seasoning or arranging ingredients. Capture each action separately for edit points.',tag:'Hands / process'},
 {group:'story',title:'Knife work / chopping close-up',instruction:'Film controlled chopping from a safe angle, keeping fingers and food in frame. Do not ask staff to change their normal safe technique.',tag:'Process detail'},
 {group:'story',title:'Stove ignition / burner turning on',instruction:'If safe and permitted, capture the burner being switched on and the flame appearing. Film from a safe distance; never stage unsafe gas handling.',tag:'Cinematic action'},
 {group:'story',title:'Wok heating / preheat',instruction:'Capture the wok heating before ingredients go in. Get one wide kitchen context shot and one close detail, only from a safe filming position.',tag:'Chinese kitchen'},
 {group:'story',title:'Oil entering hot wok',instruction:'If this is part of the real cooking process, film the oil pour from a safe angle and keep hands and camera away from heat and splashes.',tag:'Pour / process'},
 {group:'story',title:'Ingredients dropped into wok',instruction:'Capture ingredients entering the wok in one continuous take. Get a wider action shot and a tighter detail if safe.',tag:'Chinese kitchen / action'},
 {group:'story',title:'Wok toss / flame flare',instruction:'Capture the chef tossing ingredients or a natural flame flare only if this is routine and safe. Do not ask anyone to create a bigger flame for camera.',tag:'Signature action'},
 {group:'story',title:'Stir-fry from above / side',instruction:'Record the movement of ingredients being tossed and stirred. Try one over-the-shoulder view and one tight side angle.',tag:'Process coverage'},
 {group:'story',title:'Sizzle / steam close-up',instruction:'Capture the sound and visual detail of sizzling food or rising steam. Keep equipment protected and do not place the camera over the heat.',tag:'Sensory / sound'},
 {group:'story',title:'Sauce added to pan or wok',instruction:'Film the sauce going into the pan and coating the ingredients. Keep the pour visible and capture the food reaction in the pan.',tag:'Process action'},
 {group:'story',title:'Flipping / turning food',instruction:'Capture a natural flip, turn or toss as the food cooks. Use a wider angle first, then a close-up if the action can be repeated safely.',tag:'Action'},
 {group:'story',title:'Grill marks / food on grill',instruction:'Capture food being placed or turned on the grill, plus a close-up of the cooked surface. Stay clear of hot surfaces and smoke.',tag:'Kitchen action'},
 {group:'story',title:'Frying basket lift / draining',instruction:'If relevant, capture the basket lifting from the fryer and food draining. Film from the designated safe area only.',tag:'Kitchen action'},
 {group:'story',title:'Noodles lifted from wok or pot',instruction:'Capture noodles being lifted with tongs or chopsticks, showing length, steam and movement. Get one tight shot and one wider context take.',tag:'Chinese kitchen / food action'},
 {group:'story',title:'Plating from chef perspective',instruction:'Film the chef assembling the dish: base, protein, sauce, garnish and final adjustment. Capture each step as a separate edit-friendly clip.',tag:'Plating sequence'},
 {group:'story',title:'Chef final inspection / hand-off',instruction:'Capture the finished dish being checked and handed to service. Include the chef’s hands and the dish, not just a distant wide shot.',tag:'Kitchen-to-table'},
 {group:'story',title:'Packaging an order',instruction:'Film the food being packed, container closing, bagging and order hand-off. Keep the brand and food visible and protect customer details.',tag:'Takeaway process'},
 {group:'story',title:'Staff at work portrait',instruction:'Capture a natural portrait or medium shot of the chef or team member working. Ask permission and avoid disrupting service.',tag:'People / brand story'},
 // DRINKS AND POURING (kept in food group for selection logic)
 {group:'food',title:'Drink hero shot — glass and garnish',instruction:'Frame the whole drink with garnish, condensation and glass shape visible. Capture a clean static take and a slow push-in.',tag:'Beverage hero'},
 {group:'food',title:'Liquid pour into glass',instruction:'Film the drink being poured with the stream clearly visible. Use a side or 45-degree angle and repeat at a slower pace if practical.',tag:'Pour / slow motion'},
 {group:'food',title:'Ice drop / fizz / bubbles',instruction:'Capture ice dropping into the glass, bubbles rising or carbonation fizzing where relevant. Keep the glass clean and the background simple.',tag:'Beverage detail'},
 {group:'food',title:'Condensation / glass macro',instruction:'Get a tight shot of droplets, froth, bubbles, garnish or the rim of the glass. Focus on one detail at a time.',tag:'Macro'},
 {group:'food',title:'Stir / swirl / garnish drink',instruction:'Capture a spoon stirring, liquid swirling or garnish being added. Use a controlled movement and a clean background.',tag:'Beverage action'},
 {group:'food',title:'Straw / sip / first taste',instruction:'Capture a hand lifting the drink and a natural sip or first taste, with permission. Avoid making the person look directly at camera unless intended.',tag:'Lifestyle / reaction'},
 {group:'food',title:'Drink beside food pairing',instruction:'Show the drink beside the dish or combo it complements. Capture overhead and 45-degree versions for menu or ad use.',tag:'Pairing / combo'},
 // SNACKS, BAKERY, DESSERTS AND PACKAGED FOOD
 {group:'food',title:'Snack held up to camera',instruction:'Hold the snack close to the lens, then bring it back to reveal its size and shape. Keep branding or filling visible where relevant.',tag:'Snack / product'},
 {group:'food',title:'Bite into snack',instruction:'Capture a natural bite from a clean side angle, then a tighter shot of the bite mark or exposed filling. Get consent from the person.',tag:'Bite action'},
 {group:'food',title:'Break snack in half',instruction:'Break a meat pie, pastry, cookie or similar item into two pieces to reveal the inside. Frame the hands and filling clearly.',tag:'Break / reveal'},
 {group:'food',title:'Pastry flake / crumb detail',instruction:'Capture flaky layers, crumbs or a crisp outer texture in close-up. Use a dark or uncluttered background if it helps the detail stand out.',tag:'Texture macro'},
 {group:'food',title:'Filling reveal / cross-section',instruction:'Cut the snack or dessert cleanly and show the cross-section, filling and layers. Keep the cut face aimed towards the camera.',tag:'Product detail'},
 {group:'food',title:'Chocolate / syrup / cream drizzle',instruction:'Capture a controlled drizzle over the dessert or pastry. Start before the pour and hold after it ends for clean edit handles.',tag:'Pour / finishing'},
 {group:'food',title:'Dough shaping / rolling',instruction:'For bakery brands, film hands kneading, rolling, cutting or shaping dough. Capture both a close-up and a wider work-surface view.',tag:'Bakery process'},
 {group:'food',title:'Tray coming out of oven',instruction:'If safe and part of the normal process, capture the tray being removed and the finished bake revealed. Keep camera and operator clear of heat.',tag:'Bakery process'},
 {group:'food',title:'Steam or crumb as item is opened',instruction:'Capture the pastry or hot snack being opened to reveal its centre. Only use natural heat/steam; prioritise safe handling.',tag:'Sensory reveal'},
 {group:'food',title:'Scoop / slice dessert',instruction:'Film a spoon scooping a dessert or a knife cutting a cake slice. Capture the utensil entering, lifting and revealing the texture.',tag:'Dessert action'},
 {group:'food',title:'Ice cream scoop / curl',instruction:'Capture a scoop being formed or lifted, with texture in focus. Work quickly and keep the product looking true to how it is served.',tag:'Dessert action'},
 {group:'food',title:'Layered dessert cross-section',instruction:'Show the layers in parfait, cake, pudding or similar products. Shoot straight-on and at 45 degrees with a clean background.',tag:'Layers'},
 {group:'food',title:'Package open / product reveal',instruction:'Film the package opening and product being revealed. Get a close-up of the packaging details and a wider shot of the full product.',tag:'Unboxing'},
 {group:'food',title:'Product in hand for scale',instruction:'Show the packaged product held naturally to communicate its real size. Keep label facing camera and avoid misleading scale.',tag:'Packaged product'},
 {group:'food',title:'Label / seal / brand close-up',instruction:'Capture the product name, label, seal or packaging design sharply. Avoid exposing private customer information.',tag:'Packaging detail'},
 {group:'food',title:'Multiple flavours / SKUs lineup',instruction:'Arrange available flavours or product variants in a clear lineup. Capture one symmetrical shot and one moving pass across the range.',tag:'Range / lineup'},
 // CUSTOMER EXPERIENCE
 {group:'experience',title:'Menu browse / choosing a dish',instruction:'Capture a guest browsing the menu or pointing to a dish. Use a natural over-the-shoulder angle and obtain permission.',tag:'Customer journey'},
 {group:'experience',title:'Order placed / staff interaction',instruction:'Capture a natural ordering moment, hand gesture or friendly staff interaction. Avoid recording private payment details.',tag:'People'},
 {group:'experience',title:'Food served to table',instruction:'Film the server carrying and placing the dish, with a clean entry into frame. Capture guest POV and side angle.',tag:'Service action'},
 {group:'experience',title:'Hands passing / sharing dishes',instruction:'Capture a dish being passed across the table or sides being shared. Keep hands and food in focus.',tag:'Lifestyle'},
 {group:'experience',title:'Cutlery picks up first bite',instruction:'Capture the first bite being picked up and brought towards the guest. This can be filmed without showing the face.',tag:'POV'},
 {group:'experience',title:'Friends / family dining wide',instruction:'Capture a natural table interaction with food visible. Obtain consent from identifiable people before filming or publishing.',tag:'Lifestyle'},
 {group:'experience',title:'Natural reaction / enjoyment',instruction:'Capture a genuine smile, nod or conversation after tasting. Avoid directing exaggerated reactions.',tag:'Reaction'},
 {group:'experience',title:'Takeaway hand-off',instruction:'Film staff handing a packed order to a customer or rider, without showing private order details or vehicle plates unnecessarily.',tag:'Customer journey'},
 {group:'experience',title:'Payment / checkout moment',instruction:'If useful, capture a generic checkout interaction without filming PINs, card details, screens or sensitive information.',tag:'Service'},
 // PROMO / BRAND / EDIT COVERAGE
 {group:'promo',title:'Offer hero composition',instruction:'Arrange every item included in the offer in one clear frame. Ensure the visual matches the actual offer terms and portions.',tag:'Promotion hero'},
 {group:'promo',title:'Value / quantity proof shot',instruction:'Show the included items together so viewers can understand the bundle. Do not add props or portions that customers will not receive.',tag:'Value proof'},
 {group:'promo',title:'Best seller / signature item',instruction:'Give the featured product its own hero shot, close-up and action shot so it can work as a standalone post or ad.',tag:'Product focus'},
 {group:'promo',title:'Vertical 9:16 shot with text space',instruction:'Compose vertically with clean negative space at the top or bottom for offer text. Keep the product away from likely interface overlays.',tag:'Ad-ready'},
 {group:'promo',title:'Square / 4:5 social crop safety',instruction:'Capture a slightly wider composition with the hero subject centred enough to crop to 4:5 or square without losing key details.',tag:'Multi-format'},
 {group:'promo',title:'CTA end frame',instruction:'Capture a stable shot with clear space for “Order now”, location, price or booking details to be added in editing.',tag:'Call to action'},
 {group:'story',title:'Logo / brand touchpoint',instruction:'Capture the logo on packaging, menu, uniform or signage in context. Get a clean readable shot and a more natural lifestyle version.',tag:'Brand'},
 {group:'story',title:'Owner / chef portrait',instruction:'Capture a relaxed medium portrait of the owner or chef in their environment. Ask them to repeat a natural working action if needed.',tag:'Founder story'},
 {group:'story',title:'Signature process sequence',instruction:'Record the key steps that make this product or restaurant distinctive. Film each step as a separate 5–8 second clip.',tag:'Story sequence'},
 {group:'story',title:'Local / cultural detail',instruction:'Capture a genuine detail that expresses the brand’s food culture, ingredients or local identity without staging something inauthentic.',tag:'Brand story'},
 {group:'general',title:'Wide, medium and tight coverage',instruction:'For the most important action, capture a wide context shot, a medium shot and a tight detail. This gives the editor options and smoother cuts.',tag:'Coverage rule'},
 {group:'general',title:'Static safety take',instruction:'Repeat the key action with the camera locked off or held very steady. Keep rolling a few seconds before and after the action.',tag:'Edit safety'},
 {group:'general',title:'Slow-motion version',instruction:'Repeat the most visual action in slow motion if your camera supports it: pour, lift, toss, break, drizzle or plate landing.',tag:'Slow motion'},
 {group:'general',title:'Natural sound / ambience recording',instruction:'Record 10–15 seconds of clean sound: sizzling, chopping, pouring, room ambience or packaging. Avoid talking over the sound.',tag:'Sound design'},
 {group:'general',title:'Thumbnail / cover frame',instruction:'Capture a clean composition that reads clearly on a small phone screen. Keep the hero subject prominent and avoid busy backgrounds.',tag:'Cover / thumbnail'},
 {group:'general',title:'Alternate movement / angle',instruction:'Repeat the strongest shot from a different angle or with a different movement, so the edit has a genuine alternative.',tag:'Safety variation'},
 {group:'general',title:'Clean final hero shot',instruction:'Finish with the best-looking product or restaurant frame. Hold steady for at least 5 seconds and keep the composition uncluttered.',tag:'Final hero'}
];
let data = loadData(), activeId = null, editingProjectId = null, toastTimer;
function loadData(){try{return JSON.parse(localStorage.getItem(STORE_KEY))||{projects:[]}}catch{return {projects:[]}}}
function saveData(){localStorage.setItem(STORE_KEY,JSON.stringify(data));renderRecent()}
function id(){return 's_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
function selectedObjectives(){return $$('#objectiveChoices input:checked').map(x=>x.value)}
function makeShots(objectives, businessType='Restaurant'){let keys=new Set(objectives.filter(x=>x!=='challenge'));if(!keys.size)keys.add('food');let list=SHOTS.filter(s=>keys.has(s.group)||s.group==='general');const isChinese=/chinese/i.test(businessType), isBakery=/bakery|dessert|food product/i.test(businessType), isCafe=/café|cafe|bar|lounge/i.test(businessType);if(isChinese && keys.has('story'))list=list.filter(s=>true);if(objectives.includes('challenge') && objectives.filter(x=>x!=='challenge').length===0){const preferred=['Exterior establishing wide','Interior reveal — wide','Hero dish — clean static frame','Top-down / overhead food shot','Macro texture close-up','Fork / spoon / chopstick lift','Food served to table','Vertical 9:16 shot with text space','Clean final hero shot'];list=SHOTS.filter(s=>preferred.includes(s.title));}if(objectives.includes('challenge') && objectives.filter(x=>x!=='challenge').length>0){/* Challenge adds no truncation when combined with other objectives. */}return list.map(s=>({...s,id:id(),done:false,custom:false})).filter((s,i,a)=>a.findIndex(x=>x.title===s.title)===i)}
function createProject(){const name=$('#restaurantName').value.trim();if(!name){$('#restaurantName').focus();return}const objectives=selectedObjectives();if(!objectives.length){showToast('Choose at least one shoot objective.');return}const p={id:id(),name,type:$('#restaurantType').value,date:$('#shootDate').value||new Date().toISOString().slice(0,10),objectives,created:new Date().toISOString(),shots:makeShots(objectives,$('#restaurantType').value),status:'active'};data.projects.unshift(p);activeId=p.id;saveData();renderProject();$('#workspace').classList.remove('hidden');$('#setupPanel').classList.add('hidden');$('#workspace').scrollIntoView({behavior:'smooth',block:'start'});}
function activeProject(){return data.projects.find(p=>p.id===activeId)}
function renderProject(){const p=activeProject();if(!p)return;$('#projectTitle').textContent=p.name;$('#projectMeta').textContent=`${p.type} · ${formatDate(p.date)} · ${p.shots.length} shots`;const done=p.shots.filter(s=>s.done).length,total=p.shots.length,percent=total?Math.round(done/total*100):0;$('#progressNumbers').textContent=`${done} / ${total} shots`;$('#progressPercent').textContent=percent+'%';$('#progressBar').style.width=percent+'%';$('#remainingText').textContent=done===total?'All shots captured. Great work!':`${total-done} shot${total-done===1?'':'s'} left to capture`;const groupOrder=['space','food','experience','promo','story','general'];let html='';for(const g of groupOrder){const shots=p.shots.filter(s=>s.group===g);if(!shots.length)continue;const meta=GROUPS[g]||GROUPS.general;const n=shots.filter(s=>s.done).length;html+=`<section class="shot-group"><div class="group-head"><div class="group-title"><span>${meta.icon}</span>${meta.title}</div><span class="group-count">${n}/${shots.length} done</span></div>`;shots.forEach(s=>{const num=p.shots.indexOf(s)+1;html+=`<div class="shot-row ${s.done?'done':''}"><input class="shot-check" type="checkbox" data-shot="${s.id}" ${s.done?'checked':''} aria-label="Mark ${esc(s.title)} complete"><div class="shot-body"><div class="shot-title">${esc(s.title)} <span class="shot-number">#${String(num).padStart(2,'0')}</span></div><div class="shot-instruction">${esc(s.instruction||'Capture this shot clearly.')}</div>${s.tag?`<span class="shot-tag">${esc(s.tag)}</span>`:''}</div>${s.custom?`<button class="delete-shot" data-delete="${s.id}" aria-label="Delete shot">×</button>`:''}</div>`});html+='</section>'}$('#shotGroups').innerHTML=html;$$('[data-shot]').forEach(el=>el.addEventListener('change',()=>{const shot=p.shots.find(s=>s.id===el.dataset.shot);if(shot){shot.done=el.checked;saveData();renderProject()}}));$$('[data-delete]').forEach(el=>el.addEventListener('click',()=>{p.shots=p.shots.filter(s=>s.id!==el.dataset.delete);saveData();renderProject()}));}
function formatDate(d){if(!d)return 'Date not set';const dt=new Date(d+'T12:00:00');return dt.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function renderRecent(){const el=$('#recentList');if(!data.projects.length){el.innerHTML='<div class="empty-state">Your saved shoots will appear here. Create a shoot above to get started. Shoots are stored in this browser on this device.</div>';return}el.innerHTML=data.projects.slice(0,8).map(p=>{const done=p.shots.filter(s=>s.done).length;return `<div class="recent-item"><div><b>${esc(p.name)}</b><small>${esc(p.type)} · ${formatDate(p.date)}</small></div><span class="recent-progress">${done}/${p.shots.length}</span><div class="recent-actions"><button class="outline-button" data-open="${p.id}">Open</button><button class="outline-button" data-copy="${p.id}">Copy</button></div></div>`}).join('');$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.open)));$$('[data-copy]').forEach(b=>b.addEventListener('click',()=>{const p=data.projects.find(x=>x.id===b.dataset.copy);const c={...p,id:id(),name:p.name+' (copy)',created:new Date().toISOString(),shots:p.shots.map(s=>({...s,id:id(),done:false}))};data.projects.unshift(c);activeId=c.id;saveData();openProject(c.id);showToast('Shoot copied with fresh, unchecked shots.')}))}
function openProject(projectId){activeId=projectId;$('#setupPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');renderProject();$('#workspace').scrollIntoView({behavior:'smooth',block:'start'})}
function showSetup(){activeId=null;editingProjectId=null;$('#workspace').classList.add('hidden');$('#setupPanel').classList.remove('hidden');$('#restaurantName').value='';$('#shootDate').value=new Date().toISOString().slice(0,10);$('#setupPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function exportProject(){const p=activeProject();if(!p)return;let lines=[`SHOT LIST — ${p.name}`,`${p.type} | ${formatDate(p.date)}`,`Progress: ${p.shots.filter(s=>s.done).length}/${p.shots.length} completed`,''];let groups=['space','food','experience','promo','story','general'];groups.forEach(g=>{const ss=p.shots.filter(s=>s.group===g);if(!ss.length)return;lines.push((GROUPS[g]||GROUPS.general).title.toUpperCase());ss.forEach((s,i)=>lines.push(`${s.done?'[x]':'[ ]'} ${s.title} — ${s.instruction}`));lines.push('')});const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${p.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-shot-list.txt`;a.click();URL.revokeObjectURL(a.href);showToast('Checklist exported as a text file.')}
$('#shootForm').addEventListener('submit',e=>{e.preventDefault();if(editingProjectId){const p=data.projects.find(x=>x.id===editingProjectId);if(!p)return;p.name=$('#restaurantName').value.trim();p.type=$('#restaurantType').value;p.date=$('#shootDate').value||p.date;p.objectives=selectedObjectives();saveData();activeId=p.id;editingProjectId=null;$('#setupPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');renderProject();showToast('Shoot details updated.')}else{createProject()}});$('#objectiveChoices').addEventListener('change',e=>{if(e.target.matches('input'))e.target.closest('.mode-card').classList.toggle('selected',e.target.checked)});$('#newShootTop').addEventListener('click',showSetup);$('#editShoot').addEventListener('click',()=>{const p=activeProject();if(!p)return;editingProjectId=p.id;$('#restaurantName').value=p.name;$('#restaurantType').value=p.type;$('#shootDate').value=p.date;$$('#objectiveChoices input').forEach(x=>{x.checked=p.objectives.includes(x.value);x.closest('.mode-card').classList.toggle('selected',x.checked)});$('#setupPanel').classList.remove('hidden');$('#workspace').classList.add('hidden');$('#setupPanel').scrollIntoView({behavior:'smooth',block:'start'});});$('#resetChecks').addEventListener('click',()=>{const p=activeProject();if(!p)return;p.shots.forEach(s=>s.done=false);saveData();renderProject();showToast('All checks reset.')});$('#addShot').addEventListener('click',()=>{$('#shotForm').reset();$('#shotDialog').showModal();$('#shotTitle').focus()});$('#shotForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const p=activeProject();if(!p)return;const title=$('#shotTitle').value.trim();if(!title)return;p.shots.push({id:id(),group:$('#shotGroup').value,title,instruction:$('#shotInstruction').value.trim(),tag:'Custom shot',done:false,custom:true});$('#shotDialog').close();saveData();renderProject();showToast('Shot added to your checklist.')});$('#exportBtn').addEventListener('click',exportProject);$('#exportPdfBtn').addEventListener('click',()=>{if(!activeProject())return;document.body.classList.add('printing-shotlist');window.print();setTimeout(()=>document.body.classList.remove('printing-shotlist'),1000)});$('#finishBtn').addEventListener('click',()=>{const p=activeProject();if(!p)return;p.status='finished';saveData();showToast(p.shots.every(s=>s.done)?'Shoot complete. Nice work!':'Shoot saved. You can return to it any time.');renderProject()});$('#clearHistory').addEventListener('click',()=>{if(!data.projects.length)return;if(confirm('Delete all saved shoots from this browser? This cannot be undone.')){data={projects:[]};activeId=null;saveData();showSetup();showToast('Saved shoot history cleared.')}});$('#shootDate').value=new Date().toISOString().slice(0,10);renderRecent();
