const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const STORE_KEY = 'zentrik_shotlist_v1';
const GROUPS = {
  space:{title:'Space & ambience',icon:'⌂'}, food:{title:'Food & menu',icon:'✳'}, experience:{title:'Customer experience',icon:'♡'}, promo:{title:'Offer or promotion',icon:'↗'}, story:{title:'Brand story',icon:'✎'}, general:{title:'Extra shots',icon:'＋'}
};
const SHOTS = [
 {group:'space',title:'Exterior wide',instruction:'Capture the restaurant entrance and signage. Keep the full entrance in frame; hold steady for 5 seconds.',tag:'Establishing shot'},
 {group:'space',title:'Entrance / walk-in',instruction:'Capture a smooth move towards or through the entrance, if access and space allow.',tag:'Movement'},
 {group:'space',title:'Interior reveal',instruction:'Reveal the seating, decor and overall atmosphere with a slow, steady pan or push.',tag:'Establishing shot'},
 {group:'space',title:'Room details',instruction:'Capture 2–3 details: lighting, tables, wall art, menu boards or distinctive decor.',tag:'Detail'},
 {group:'space',title:'Wide dining-space shot',instruction:'Show the layout and ambience. Avoid blocking walkways or disrupting guests.',tag:'Wide'},
 {group:'food',title:'Hero dish reveal',instruction:'Start with a clean frame, then reveal the full dish. Remove distracting items from the background.',tag:'Hero shot'},
 {group:'food',title:'45-degree dish angle',instruction:'Capture the dish at a natural dining angle to show its height, toppings and presentation.',tag:'Angle variation'},
 {group:'food',title:'Overhead dish shot',instruction:'Frame the complete dish from directly above. Keep the plate level and the composition tidy.',tag:'Angle variation'},
 {group:'food',title:'Texture close-up',instruction:'Move in close to show the most appetising textures and ingredients. Keep focus on the food.',tag:'Macro / detail'},
 {group:'food',title:'Fork, spoon or chopstick lift',instruction:'Lift one appealing bite slowly towards the camera. Capture a few takes with clean movement.',tag:'Food action'},
 {group:'food',title:'Sauce pour or finishing touch',instruction:'If relevant, capture sauce, seasoning, garnish or a finishing touch being added.',tag:'Food action'},
 {group:'food',title:'Steam / fresh-from-kitchen moment',instruction:'If steam is naturally visible, capture it against a darker or uncluttered background.',tag:'Sensory detail'},
 {group:'food',title:'Dish arrives at the table',instruction:'Capture the plate being placed down, ideally from a guest’s point of view.',tag:'Food action'},
 {group:'food',title:'Full meal with accompaniments',instruction:'Show the dish with its sides, drinks or sauces to communicate the full serving.',tag:'Menu'},
 {group:'experience',title:'Order or menu interaction',instruction:'Capture a natural moment of someone browsing the menu or placing an order. Ask permission first.',tag:'People'},
 {group:'experience',title:'Staff serving a meal',instruction:'Capture the hand-off or serving moment with the dish clearly visible.',tag:'Service'},
 {group:'experience',title:'Dining moment',instruction:'Film a natural, comfortable dining interaction. Obtain consent before featuring identifiable guests.',tag:'People'},
 {group:'experience',title:'Hands sharing / passing food',instruction:'Capture hands passing a dish, pouring a drink or sharing food for a welcoming feel.',tag:'Lifestyle'},
 {group:'promo',title:'Offer hero frame',instruction:'Capture the complete bundle or promotion clearly, with all included items visible.',tag:'Promotion'},
 {group:'promo',title:'Value / quantity shot',instruction:'Show what the customer receives. Arrange items neatly without misrepresenting portion sizes.',tag:'Offer detail'},
 {group:'promo',title:'Vertical frame with text space',instruction:'Compose a clean 9:16 shot with negative space for offer details or a call to action.',tag:'Ad-ready'},
 {group:'story',title:'Chef or team at work',instruction:'Capture a genuine preparation or service moment. Confirm staff are comfortable being filmed.',tag:'Behind the scenes'},
 {group:'story',title:'Preparation process',instruction:'Film a useful process detail: chopping, stirring, plating or packing, depending on the brand.',tag:'Behind the scenes'},
 {group:'story',title:'Brand signature detail',instruction:'Capture a recognisable brand touchpoint such as packaging, uniform, logo or distinctive presentation.',tag:'Brand'},
 {group:'general',title:'Alternate hero take',instruction:'Repeat the strongest shot with a different angle or camera movement for editing flexibility.',tag:'Safety take'},
 {group:'general',title:'Clean end frame',instruction:'Capture a stable final frame that could work as an ending, cover or thumbnail.',tag:'Edit-ready'}
];
let data = loadData(), activeId = null, editingProjectId = null, toastTimer;
function loadData(){try{return JSON.parse(localStorage.getItem(STORE_KEY))||{projects:[]}}catch{return {projects:[]}}}
function saveData(){localStorage.setItem(STORE_KEY,JSON.stringify(data));renderRecent()}
function id(){return 's_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}
function selectedObjectives(){return $$('#objectiveChoices input:checked').map(x=>x.value)}
function makeShots(objectives){let keys=new Set(objectives.filter(x=>x!=='challenge'));if(!keys.size)keys.add('food');let list=SHOTS.filter(s=>keys.has(s.group)||s.group==='general');if(objectives.includes('challenge')){const preferred=['Exterior wide','Interior reveal','Hero dish reveal','Texture close-up','Fork, spoon or chopstick lift','Dish arrives at the table','Vertical frame with text space','Clean end frame'];list=SHOTS.filter(s=>preferred.includes(s.title));}return list.map(s=>({...s,id:id(),done:false,custom:false}))}
function createProject(){const name=$('#restaurantName').value.trim();if(!name){$('#restaurantName').focus();return}const objectives=selectedObjectives();if(!objectives.length){showToast('Choose at least one shoot objective.');return}const p={id:id(),name,type:$('#restaurantType').value,date:$('#shootDate').value||new Date().toISOString().slice(0,10),objectives,created:new Date().toISOString(),shots:makeShots(objectives),status:'active'};data.projects.unshift(p);activeId=p.id;saveData();renderProject();$('#workspace').classList.remove('hidden');$('#setupPanel').classList.add('hidden');$('#workspace').scrollIntoView({behavior:'smooth',block:'start'});}
function activeProject(){return data.projects.find(p=>p.id===activeId)}
function renderProject(){const p=activeProject();if(!p)return;$('#projectTitle').textContent=p.name;$('#projectMeta').textContent=`${p.type} · ${formatDate(p.date)} · ${p.shots.length} shots`;const done=p.shots.filter(s=>s.done).length,total=p.shots.length,percent=total?Math.round(done/total*100):0;$('#progressNumbers').textContent=`${done} / ${total} shots`;$('#progressPercent').textContent=percent+'%';$('#progressBar').style.width=percent+'%';$('#remainingText').textContent=done===total?'All shots captured. Great work!':`${total-done} shot${total-done===1?'':'s'} left to capture`;const groupOrder=['space','food','experience','promo','story','general'];let html='';for(const g of groupOrder){const shots=p.shots.filter(s=>s.group===g);if(!shots.length)continue;const meta=GROUPS[g]||GROUPS.general;const n=shots.filter(s=>s.done).length;html+=`<section class="shot-group"><div class="group-head"><div class="group-title"><span>${meta.icon}</span>${meta.title}</div><span class="group-count">${n}/${shots.length} done</span></div>`;shots.forEach(s=>{const num=p.shots.indexOf(s)+1;html+=`<div class="shot-row ${s.done?'done':''}"><input class="shot-check" type="checkbox" data-shot="${s.id}" ${s.done?'checked':''} aria-label="Mark ${esc(s.title)} complete"><div class="shot-body"><div class="shot-title">${esc(s.title)} <span class="shot-number">#${String(num).padStart(2,'0')}</span></div><div class="shot-instruction">${esc(s.instruction||'Capture this shot clearly.')}</div>${s.tag?`<span class="shot-tag">${esc(s.tag)}</span>`:''}</div>${s.custom?`<button class="delete-shot" data-delete="${s.id}" aria-label="Delete shot">×</button>`:''}</div>`});html+='</section>'}$('#shotGroups').innerHTML=html;$$('[data-shot]').forEach(el=>el.addEventListener('change',()=>{const shot=p.shots.find(s=>s.id===el.dataset.shot);if(shot){shot.done=el.checked;saveData();renderProject()}}));$$('[data-delete]').forEach(el=>el.addEventListener('click',()=>{p.shots=p.shots.filter(s=>s.id!==el.dataset.delete);saveData();renderProject()}));}
function formatDate(d){if(!d)return 'Date not set';const dt=new Date(d+'T12:00:00');return dt.toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function renderRecent(){const el=$('#recentList');if(!data.projects.length){el.innerHTML='<div class="empty-state">Your saved shoots will appear here. Create a shoot above to get started. Shoots are stored in this browser on this device.</div>';return}el.innerHTML=data.projects.slice(0,8).map(p=>{const done=p.shots.filter(s=>s.done).length;return `<div class="recent-item"><div><b>${esc(p.name)}</b><small>${esc(p.type)} · ${formatDate(p.date)}</small></div><span class="recent-progress">${done}/${p.shots.length}</span><div class="recent-actions"><button class="outline-button" data-open="${p.id}">Open</button><button class="outline-button" data-copy="${p.id}">Copy</button></div></div>`}).join('');$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openProject(b.dataset.open)));$$('[data-copy]').forEach(b=>b.addEventListener('click',()=>{const p=data.projects.find(x=>x.id===b.dataset.copy);const c={...p,id:id(),name:p.name+' (copy)',created:new Date().toISOString(),shots:p.shots.map(s=>({...s,id:id(),done:false}))};data.projects.unshift(c);activeId=c.id;saveData();openProject(c.id);showToast('Shoot copied with fresh, unchecked shots.')}))}
function openProject(projectId){activeId=projectId;$('#setupPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');renderProject();$('#workspace').scrollIntoView({behavior:'smooth',block:'start'})}
function showSetup(){activeId=null;editingProjectId=null;$('#workspace').classList.add('hidden');$('#setupPanel').classList.remove('hidden');$('#restaurantName').value='';$('#shootDate').value=new Date().toISOString().slice(0,10);$('#setupPanel').scrollIntoView({behavior:'smooth',block:'start'})}
function exportProject(){const p=activeProject();if(!p)return;let lines=[`SHOT LIST — ${p.name}`,`${p.type} | ${formatDate(p.date)}`,`Progress: ${p.shots.filter(s=>s.done).length}/${p.shots.length} completed`,''];let groups=['space','food','experience','promo','story','general'];groups.forEach(g=>{const ss=p.shots.filter(s=>s.group===g);if(!ss.length)return;lines.push((GROUPS[g]||GROUPS.general).title.toUpperCase());ss.forEach((s,i)=>lines.push(`${s.done?'[x]':'[ ]'} ${s.title} — ${s.instruction}`));lines.push('')});const blob=new Blob([lines.join('\n')],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${p.name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-shot-list.txt`;a.click();URL.revokeObjectURL(a.href);showToast('Checklist exported as a text file.')}
$('#shootForm').addEventListener('submit',e=>{e.preventDefault();if(editingProjectId){const p=data.projects.find(x=>x.id===editingProjectId);if(!p)return;p.name=$('#restaurantName').value.trim();p.type=$('#restaurantType').value;p.date=$('#shootDate').value||p.date;p.objectives=selectedObjectives();saveData();activeId=p.id;editingProjectId=null;$('#setupPanel').classList.add('hidden');$('#workspace').classList.remove('hidden');renderProject();showToast('Shoot details updated.')}else{createProject()}});$('#objectiveChoices').addEventListener('change',e=>{if(e.target.matches('input'))e.target.closest('.mode-card').classList.toggle('selected',e.target.checked)});$('#newShootTop').addEventListener('click',showSetup);$('#editShoot').addEventListener('click',()=>{const p=activeProject();if(!p)return;editingProjectId=p.id;$('#restaurantName').value=p.name;$('#restaurantType').value=p.type;$('#shootDate').value=p.date;$$('#objectiveChoices input').forEach(x=>{x.checked=p.objectives.includes(x.value);x.closest('.mode-card').classList.toggle('selected',x.checked)});$('#setupPanel').classList.remove('hidden');$('#workspace').classList.add('hidden');$('#setupPanel').scrollIntoView({behavior:'smooth',block:'start'});});$('#resetChecks').addEventListener('click',()=>{const p=activeProject();if(!p)return;p.shots.forEach(s=>s.done=false);saveData();renderProject();showToast('All checks reset.')});$('#addShot').addEventListener('click',()=>{$('#shotForm').reset();$('#shotDialog').showModal();$('#shotTitle').focus()});$('#shotForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const p=activeProject();if(!p)return;const title=$('#shotTitle').value.trim();if(!title)return;p.shots.push({id:id(),group:$('#shotGroup').value,title,instruction:$('#shotInstruction').value.trim(),tag:'Custom shot',done:false,custom:true});$('#shotDialog').close();saveData();renderProject();showToast('Shot added to your checklist.')});$('#exportBtn').addEventListener('click',exportProject);$('#finishBtn').addEventListener('click',()=>{const p=activeProject();if(!p)return;p.status='finished';saveData();showToast(p.shots.every(s=>s.done)?'Shoot complete. Nice work!':'Shoot saved. You can return to it any time.');renderProject()});$('#clearHistory').addEventListener('click',()=>{if(!data.projects.length)return;if(confirm('Delete all saved shoots from this browser? This cannot be undone.')){data={projects:[]};activeId=null;saveData();showSetup();showToast('Saved shoot history cleared.')}});$('#shootDate').value=new Date().toISOString().slice(0,10);renderRecent();
